### ISSUE TITLE
[nodemon] app crashed 

### ISSUE THREAD

**Issue by pcabrera83** [Chalarangelo/node-static-page-generator#2]
I cloned your repository and encountered an issue with the app. I get this error message:  `[nodemon] app crashed - waiting for file changes before starting...`

My Steps: 

1. `git clone https://github.com/Chalarangelo/node-static-page-generator.git`
2. `npm install`
3. `npm run start`
4. `[nodemon] app crashed - waiting for file changes before starting...`

Any idea on how I can resolve this?

**Comment by richcouzzi** [comment]
Two options: 
1. update line 7 of `package.json` to be: `"build-pages": "node --harmony ./build_scripts/builder.js"`<sup>1</sup>

2. Inline polyfill<sup>2</sup> for `Object.entries`<sup>3</sup> in `build_scripts/builder.js`:

```javascript
if (!Object.entries)
   Object.entries = function( obj ){
      var ownProps = Object.keys( obj ),
         i = ownProps.length,
         resArray = new Array(i); // preallocate the Array

      while (i--)
         resArray[i] = [ownProps[i], obj[ownProps[i]]];
      return resArray;
   };
```

Then running `npm run start` should work properly.

---

<sup>1</sup> http://kangax.github.io/compat-table/es2016plus/
<sup>2</sup> https://stackoverflow.com/a/47978439/2159228
<sup>3</sup> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**Comment by Chalarangelo** [comment]
`Object.entries()` should run in most environments already. If it doesn't, you should inline the polyfill (as with any other script that uses said method). I'm closing as this is an environment-dependent bug that will go away on its own after updating node.
